package com.localserve.finance.ledger;

public enum LedgerAccountType {
    GATEWAY_RECEIVABLE,
    SETTLEMENT_BANK_CASH,
    CUSTOMER_HELD_FUNDS,
    CUSTOMER_REFUND_PAYABLE,
    PROVIDER_AVAILABLE_PAYABLE,
    PROVIDER_FROZEN_PAYABLE,
    PAYOUT_CLEARING_PAYABLE,
    COMMISSION_REVENUE,
    TAX_PAYABLE,
    CONVENIENCE_FEE_REVENUE,
    PROMO_CREDIT_LIABILITY,
    PROMOTION_EXPENSE,
    GATEWAY_FEE_EXPENSE,
    RISK_RECEIVABLE
}
