import { Filter, MapPin, ShieldCheck, SlidersHorizontal, Star } from "lucide-react";
import Link from "next/link";
import { Avatar, Badge, Button, Card, Field, Input, SearchField, SectionHeading, formatMoney } from "@localserve/ui";
import { providers } from "../../lib/preview-data";

export const metadata = { title: "Find a professional" };
export default async function SearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams;
  const results = providers.filter(item => `${item.name} ${item.service}`.toLowerCase().includes(q.toLowerCase()));
  return <div className="space-y-6"><SectionHeading eyebrow="Explore" title={q ? `Results for “${q}”` : "Find trusted professionals"} description="Prices are guidance until the server issues an expiring booking quote."/><form className="grid gap-3 rounded-[1.5rem] border border-border bg-surface p-4 shadow-sm lg:grid-cols-[1fr_180px_160px_auto]"><SearchField name="q" defaultValue={q} placeholder="Service or professional"/><Field label="Location"><Input name="location" defaultValue="Sector 62, Noida"/></Field><Field label="Sort by"><select name="sort" className="min-h-12 w-full rounded-2xl border border-border bg-surface px-3 text-sm font-bold"><option>Fastest arrival</option><option>Highest rated</option><option>Lowest price</option></select></Field><Button className="self-end"><Filter className="size-4"/>Apply</Button></form><div className="flex flex-wrap gap-2"><Badge tone="info"><MapPin className="mr-1 size-3"/>Within 5 km</Badge><Badge>Available now</Badge><Badge>Rating 4.5+</Badge><Button size="sm" variant="ghost"><SlidersHorizontal className="size-3.5"/>More filters</Button></div><div className="grid gap-4">{results.map(provider => <Card key={provider.id} className="grid gap-5 p-5 md:grid-cols-[auto_1fr_auto] md:items-center"><Avatar initials={provider.initials} size="lg"/><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black">{provider.name}</h2><ShieldCheck className="size-4 text-primary"/><Badge tone="positive">Available</Badge></div><p className="mt-1 text-sm text-muted-foreground">{provider.service} · {provider.experienceYears} years experience</p><div className="mt-3 flex flex-wrap gap-4 text-xs font-bold"><span className="flex items-center gap-1"><Star className="size-3.5 fill-amber-400 text-amber-400"/>{provider.rating} ({provider.reviewCount})</span><span>{provider.distanceKm} km away</span><span>{provider.etaMinutes} min ETA</span></div></div><div className="md:text-right"><p className="text-xs text-muted-foreground">Starts at</p><p className="text-lg font-black">{formatMoney(provider.priceFrom)}</p><Button asChild className="mt-3"><Link href={`/search?provider=${provider.id}`}>Compare offer</Link></Button></div></Card>)}{results.length === 0 && <Card className="p-10 text-center"><h2 className="font-black">No exact matches</h2><p className="mt-2 text-sm text-muted-foreground">Try a service category or broaden the location filter.</p></Card>}</div></div>;
}
