package com.localserve.booking.domain;

public enum BookingStatus {
    CREATED,
    SEARCHING_PROVIDERS,
    PROVIDERS_FOUND,
    PROVIDER_SELECTED,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    PROVIDER_ASSIGNED,
    PROVIDER_ON_THE_WAY,
    PROVIDER_ARRIVED,
    START_OTP_PENDING,
    IN_PROGRESS,
    COMPLETION_PENDING,
    CUSTOMER_CONFIRMATION_PENDING,
    COMPLETED,
    DISPUTED,
    CANCELLED,
    REFUNDED,
    CLOSED
}
