import { ArrowRight, BriefcaseBusiness, CheckCircle2, Clock3, IndianRupee, MapPin, Navigation, ShieldCheck, Star, TrendingUp } from "lucide-react";
import Link from "next/link";
import { Badge, Button, Card, CardContent, CardHeader, Progress, SectionHeading, StatCard, formatMoney } from "@localserve/ui";
import { AvailabilityControl } from "./_components/availability-control";

const inr = (amountMinor: number) => ({ amountMinor, currency: "INR" });
export default function ProviderDashboard() { return <div className="space-y-7"><SectionHeading eyebrow="Provider workspace" title="Ready for a productive day, Ravi?" description="Your eligibility, current work, requests and ledger-derived earnings in one place." action={<AvailabilityControl initialOnline/>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Today's earnings" value={formatMoney(inr(348500))} detail="3 completed services" trend="up" icon={IndianRupee}/><StatCard label="New requests" value="4" detail="Nearest is 1.8 km away" icon={BriefcaseBusiness}/><StatCard label="Acceptance rate" value="92%" detail="Up 3.2% this month" trend="up" icon={TrendingUp}/><StatCard label="Average rating" value="4.9" detail="438 verified reviews" icon={Star}/></div>
<div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card className="overflow-hidden border-primary/25"><div className="bg-primary px-5 py-3 text-xs font-extrabold uppercase tracking-[.16em] text-primary-foreground">New nearby request · expires in 01:42</div><CardContent className="pt-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="text-xl font-black">AC cooling inspection</h2><Badge tone="danger">Emergency</Badge></div><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4"/>Sector 62 service area · 1.8 km</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Customer budget</p><p className="text-xl font-black">₹900–₹1,400</p></div></div><div className="mt-5 grid grid-cols-3 divide-x divide-border rounded-2xl bg-surface-subtle py-4 text-center"><div><p className="font-black">12 min</p><p className="text-[.65rem] text-muted-foreground">Route ETA</p></div><div><p className="font-black">4.8</p><p className="text-[.65rem] text-muted-foreground">Customer</p></div><div><p className="font-black">Instant</p><p className="text-[.65rem] text-muted-foreground">Booking type</p></div></div><p className="mt-4 rounded-2xl bg-info-soft p-3 text-xs font-semibold leading-5 text-info">Exact address and contact remain hidden until the customer selects your offer and verified payment is held.</p><div className="mt-5 flex gap-3"><Button asChild><Link href="/jobs">Review request <ArrowRight className="size-4"/></Link></Button><Button variant="ghost">Not interested</Button></div></CardContent></Card>
<Card><CardHeader eyebrow="Current job" title="Arrive by 2:15 PM" action={<Badge tone="info">On the way</Badge>}/><CardContent><div className="relative overflow-hidden rounded-2xl bg-[linear-gradient(135deg,var(--primary-soft),var(--surface-subtle))] p-5"><span className="absolute right-4 top-4 grid size-12 place-items-center rounded-full bg-primary text-white"><Navigation className="size-5"/></span><p className="text-xs font-bold text-muted-foreground">Booking LS-64001</p><h3 className="mt-1 font-black">AC inspection · Aarav</h3><p className="mt-2 text-sm text-muted-foreground">Sector 62, Noida</p><div className="mt-6 flex gap-3"><Button size="sm">Open navigation</Button><Button size="sm" variant="secondary">Message</Button></div></div><div className="mt-4 flex items-start gap-3 rounded-2xl border border-warning/25 bg-warning-soft p-3 text-warning"><ShieldCheck className="mt-0.5 size-4 shrink-0"/><p className="text-xs font-semibold leading-5">Ask for the Start OTP only after reaching the service address.</p></div></CardContent></Card></div>
<div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader title="Performance" action={<Link href="/earnings" className="text-xs font-extrabold text-primary">View analytics</Link>}/><CardContent className="space-y-5"><Progress value={92} label="Acceptance rate"/><Progress value={96} label="Completion rate"/><Progress value={98} label="On-time arrival"/></CardContent></Card><Card><CardHeader title="Today's schedule"/><CardContent><ol className="space-y-4">{[{time:"11:30",title:"AC gas refill",done:true},{time:"14:15",title:"AC inspection",done:false},{time:"17:00",title:"Cooling service",done:false}].map(item => <li key={item.time} className="flex items-center gap-3"><span className={`grid size-9 place-items-center rounded-xl ${item.done ? "bg-success-soft text-success" : "bg-surface-subtle text-muted-foreground"}`}>{item.done ? <CheckCircle2 className="size-4"/> : <Clock3 className="size-4"/>}</span><div className="flex-1"><p className="text-sm font-extrabold">{item.title}</p><p className="text-xs text-muted-foreground">{item.time}</p></div>{item.done && <Badge tone="positive">Done</Badge>}</li>)}</ol></CardContent></Card></div></div>; }
