import { AirVent, ArrowRight, BrushCleaning, Car, ChevronRight, Droplets, Laptop, MapPin, PaintRoller, ShieldCheck, Smartphone, Sparkles, Star, Wrench, Zap } from "lucide-react";
import Link from "next/link";
import { Avatar, Badge, BookingStatusBadge, Button, Card, CardContent, CardHeader, SearchField, SectionHeading, formatMoney } from "@localserve/ui";
import { activeBooking, providers } from "../lib/preview-data";

const services = [
  { name: "Electrician", icon: Zap, tone: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300" },
  { name: "Plumber", icon: Droplets, tone: "bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300" },
  { name: "AC repair", icon: AirVent, tone: "bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-300" },
  { name: "Cleaning", icon: BrushCleaning, tone: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" },
  { name: "Painter", icon: PaintRoller, tone: "bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300" },
  { name: "Mechanic", icon: Car, tone: "bg-orange-100 text-orange-700 dark:bg-orange-950 dark:text-orange-300" },
  { name: "Laptop", icon: Laptop, tone: "bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300" },
  { name: "Mobile", icon: Smartphone, tone: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300" },
];

export default function CustomerDashboard() {
  return <div className="space-y-8"><section className="relative overflow-hidden rounded-[2rem] bg-[linear-gradient(125deg,#075f56_0%,#087669_52%,#12a08e_100%)] p-6 text-white shadow-[0_24px_70px_-30px_rgba(8,118,105,.8)] sm:p-9"><div className="absolute -right-16 -top-20 size-64 rounded-full border-[42px] border-white/8"/><div className="absolute bottom-[-5rem] right-[22%] size-44 rounded-full bg-amber-300/15 blur-2xl"/><div className="relative max-w-2xl"><Badge className="bg-white/15 text-white">Trusted help, minutes away</Badge><h1 className="mt-4 text-balance text-3xl font-black leading-tight tracking-[-.04em] sm:text-5xl">What can we fix for you today?</h1><p className="mt-3 max-w-xl text-sm leading-6 text-emerald-50 sm:text-base">Compare verified nearby professionals, transparent estimates, and real arrival times.</p><form action="/search" className="mt-7"><SearchField name="q" aria-label="Search for a service" placeholder="Search electrician, plumber, AC repair…" className="border-white/20 bg-white text-slate-900"/></form><div className="mt-4 flex flex-wrap gap-4 text-xs font-bold text-emerald-50"><span className="flex items-center gap-1.5"><ShieldCheck className="size-4"/>Verified professionals</span><span className="flex items-center gap-1.5"><MapPin className="size-4"/>Live arrival tracking</span></div></div></section>

  <section aria-labelledby="services-heading"><SectionHeading eyebrow="Browse" title="Popular services" action={<Link href="/search" className="flex items-center gap-1 text-sm font-extrabold text-primary">View all <ArrowRight className="size-4"/></Link>}/><div className="mt-5 grid grid-cols-4 gap-3 sm:grid-cols-4 lg:grid-cols-8">{services.map(({ name, icon: Icon, tone }) => <Link key={name} href={`/search?q=${encodeURIComponent(name)}`} className="group rounded-[1.35rem] border border-border bg-surface p-3 text-center shadow-sm transition hover:-translate-y-1 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className={`mx-auto grid size-12 place-items-center rounded-2xl ${tone}`}><Icon className="size-5"/></span><span className="mt-2 block text-[.7rem] font-extrabold sm:text-xs">{name}</span></Link>)}</div></section>

  <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]" aria-labelledby="active-booking"><Card className="overflow-hidden"><CardHeader eyebrow="Active booking" title={activeBooking.serviceName} action={<BookingStatusBadge status={activeBooking.status}/>}/><CardContent><div className="grid gap-5 md:grid-cols-[1fr_220px]"><div><div className="flex items-center gap-3"><Avatar initials="RK" size="lg"/><div><p className="font-extrabold">{activeBooking.providerName}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><Star className="size-3.5 fill-amber-400 text-amber-400"/>4.9 · 438 completed jobs</p></div></div><div className="mt-6 flex items-end justify-between gap-4 rounded-2xl bg-surface-subtle p-4"><div><p className="text-xs font-bold text-muted-foreground">Estimated arrival</p><p className="mt-1 text-2xl font-black">{activeBooking.etaMinutes} min</p></div><div className="text-right"><p className="text-xs font-bold text-muted-foreground">Payment secured</p><p className="mt-1 font-black">{formatMoney(activeBooking.amount)}</p></div></div><div className="mt-5 flex gap-3"><Button asChild><Link href={`/bookings/${activeBooking.id}`}>Track booking <ChevronRight className="size-4"/></Link></Button><Button variant="secondary">Contact support</Button></div></div><div className="relative min-h-44 overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_30%_35%,#d7ece7_0_2px,transparent_3px),linear-gradient(135deg,#edf5f3,#dcece8)] bg-[size:22px_22px,auto] dark:bg-[radial-gradient(circle_at_30%_35%,#27413b_0_2px,transparent_3px),linear-gradient(135deg,#172521,#1f332e)]"><span className="absolute left-[22%] top-[65%] size-4 rounded-full border-4 border-white bg-primary shadow-lg"/><span className="absolute right-[24%] top-[25%] grid size-10 place-items-center rounded-full bg-slate-900 text-white shadow-xl"><Wrench className="size-4"/></span><span className="absolute left-[28%] top-[50%] h-1 w-[50%] -rotate-[28deg] rounded-full bg-primary/45"/><span className="absolute bottom-3 left-3 rounded-xl bg-surface/90 px-3 py-2 text-[.65rem] font-bold text-foreground shadow">Live location · updated 8 sec ago</span></div></div></CardContent></Card>
  <Card className="bg-[linear-gradient(145deg,var(--surface),var(--primary-soft))]"><CardContent className="flex h-full flex-col justify-between pt-5"><div><span className="grid size-12 place-items-center rounded-2xl bg-primary text-white"><Sparkles className="size-5"/></span><p className="mt-5 text-xs font-black uppercase tracking-[.15em] text-primary">Home care plan</p><h2 className="mt-2 text-2xl font-black tracking-tight">Save on every repair</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Priority matching, lower visit fees, and annual maintenance reminders.</p></div><Button className="mt-6 w-full" variant="secondary">Explore membership</Button></CardContent></Card></section>

  <section aria-labelledby="nearby-heading"><SectionHeading eyebrow="Near you" title="Top-rated professionals" description="Availability and ETA are refreshed before you confirm a booking."/><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{providers.map(provider => <Card key={provider.id} className="group p-5 transition hover:-translate-y-1 hover:shadow-xl"><div className="flex items-start gap-3"><Avatar initials={provider.initials} size="lg"/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate font-extrabold">{provider.name}</h3>{provider.verified && <ShieldCheck aria-label="Verified" className="size-4 text-primary"/>}</div><p className="mt-1 text-xs text-muted-foreground">{provider.service} · {provider.experienceYears} years</p><p className="mt-2 flex items-center gap-1 text-xs font-bold"><Star className="size-3.5 fill-amber-400 text-amber-400"/>{provider.rating} <span className="font-normal text-muted-foreground">({provider.reviewCount})</span></p></div></div><div className="mt-5 grid grid-cols-3 divide-x divide-border rounded-2xl bg-surface-subtle py-3 text-center"><div><p className="text-xs font-black">{provider.etaMinutes} min</p><p className="mt-1 text-[.62rem] text-muted-foreground">ETA</p></div><div><p className="text-xs font-black">{provider.distanceKm} km</p><p className="mt-1 text-[.62rem] text-muted-foreground">Away</p></div><div><p className="text-xs font-black">{formatMoney(provider.priceFrom)}</p><p className="mt-1 text-[.62rem] text-muted-foreground">Starts at</p></div></div><Button asChild className="mt-4 w-full" variant="secondary"><Link href={`/search?provider=${provider.id}`}>View profile</Link></Button></Card>)}</div></section></div>;
}
